[package]
name = "vuln"
version = "0.1.0"
authors = ["Jean Casademont <jean.casademont@gmail.com>"]

[dependencies]
hex = "0.3"
iron = "0.6"
router = "0.6"
urlencoded = "0.6"
lib = { path = "../lib" }
